import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const siteSettings = pgTable('site_settings', { id: text('id').primaryKey(), organizationName: text('organization_name').notNull(), notificationEmail: text('notification_email').notNull(), phone: text('phone'), address: text('address'), logoUrl: text('logo_url'), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const programs = pgTable('programs', { id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), category: text('category').notNull(), summary: text('summary').notNull(), description: text('description').notNull(), imageUrl: text('image_url'), active: boolean('active').notNull().default(true), status: text('status').notNull().default('published'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const impactStories = pgTable('impact_stories', { id: text('id').primaryKey(), name: text('name').notNull(), location: text('location').notNull(), quote: text('quote').notNull(), category: text('category').notNull(), imageUrl: text('image_url'), videoUrl: text('video_url'), rating: integer('rating').notNull().default(5), published: boolean('published').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() })
export const posts = pgTable('posts', { id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), type: text('type').notNull().default('news'), excerpt: text('excerpt').notNull(), content: text('content').notNull(), imageUrl: text('image_url'), published: boolean('published').notNull().default(true), publishedAt: timestamp('published_at').notNull().defaultNow() })
export const donations = pgTable('donations', { id: text('id').primaryKey(), donorName: text('donor_name').notNull(), email: text('email').notNull(), amount: integer('amount').notNull(), frequency: text('frequency').notNull().default('one-time'), reference: text('reference').notNull(), phone: text('phone'), status: text('status').notNull().default('pending'), notificationStatus: text('notification_status').notNull().default('pending'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const volunteers = pgTable('volunteers', { id: text('id').primaryKey(), firstName: text('first_name').notNull(), lastName: text('last_name').notNull(), email: text('email').notNull(), phone: text('phone').notNull(), interest: text('interest').notNull(), skills: text('skills').notNull(), status: text('status').notNull().default('new'), notificationStatus: text('notification_status').notNull().default('pending'), createdAt: timestamp('created_at').notNull().defaultNow() })

export const schema = { user, session, account, verification, siteSettings, programs, impactStories, posts, donations, volunteers }
