import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const siteSettings = pgTable('site_settings', { id: text('id').primaryKey(), organizationName: text('organization_name').notNull(), notificationEmail: text('notification_email').notNull(), phone: text('phone'), address: text('address'), logoUrl: text('logo_url'), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const homepageContent = pgTable('homepage_content', { id: text('id').primaryKey(), heroBadge: text('hero_eyebrow').notNull(), heroTitle: text('hero_title').notNull(), heroDescription: text('hero_description').notNull(), primaryCtaLabel: text('primary_cta_label').notNull(), secondaryCtaLabel: text('secondary_cta_label').notNull(), reachValue: text('people_reached').notNull(), reachLabel: text('people_reached_label').notNull(), widowsValue: text('metric_1_value').notNull(), widowsLabel: text('metric_1_label').notNull(), childrenValue: text('metric_2_value').notNull(), childrenLabel: text('metric_2_label').notNull(), elderlyValue: text('metric_3_value').notNull(), elderlyLabel: text('metric_3_label').notNull(), communitiesValue: text('metric_4_value').notNull(), communitiesLabel: text('metric_4_label').notNull(), directProgrammesPercent: integer('direct_programmes').notNull(), fundraisingPercent: integer('fundraising').notNull(), administrationPercent: integer('administration').notNull(), valuesJson: text('values_json').notNull(), transparencyNote: text('transparency_note').notNull(), donationTitle: text('donation_title').notNull().default('Give hope a place to grow.'), donationDescription: text('donation_description').notNull().default('Your gift helps provide school supplies, food, healthcare, and livelihood support where it is needed most.'), volunteerTitle: text('volunteer_title').notNull().default('Bring your gifts into the circle.'), volunteerDescription: text('volunteer_description').notNull().default('Whether you have an hour, a skill, or a heart for people, there is a place for you here.'), volunteerNote: text('volunteer_note').notNull().default('We welcome people at every stage of life. Our team will contact you to understand where you can contribute best.'), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const programs = pgTable('programs', { id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), category: text('category').notNull(), summary: text('summary').notNull(), description: text('description').notNull(), imageUrl: text('image_url'), active: boolean('active').notNull().default(true), status: text('status').notNull().default('published'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const impactStories = pgTable('impact_stories', { id: text('id').primaryKey(), name: text('name').notNull(), location: text('location').notNull(), quote: text('quote').notNull(), category: text('category').notNull(), imageUrl: text('image_url'), videoUrl: text('video_url'), rating: integer('rating').notNull().default(5), published: boolean('published').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() })
export const posts = pgTable('posts', { id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), type: text('type').notNull().default('news'), excerpt: text('excerpt').notNull(), content: text('content').notNull(), imageUrl: text('image_url'), published: boolean('published').notNull().default(true), publishedAt: timestamp('published_at').notNull().defaultNow() })
export const mediaAssets = pgTable('media_assets', { id: text('id').primaryKey(), url: text('url').notNull(), title: text('title').notNull(), description: text('description').notNull().default(''), placement: text('placement').notNull().default('homepage'), published: boolean('published').notNull().default(false), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const donations = pgTable('donations', { id: text('id').primaryKey(), donorName: text('donor_name').notNull(), email: text('email').notNull(), amount: integer('amount').notNull(), frequency: text('frequency').notNull().default('one-time'), reference: text('reference').notNull(), receiptUrl: text('receipt_url'), phone: text('phone'), status: text('status').notNull().default('pending'), notificationStatus: text('notification_status').notNull().default('pending'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const volunteers = pgTable('volunteers', { id: text('id').primaryKey(), firstName: text('first_name').notNull(), lastName: text('last_name').notNull(), email: text('email').notNull(), phone: text('phone').notNull(), interest: text('interest').notNull(), skills: text('skills').notNull(), status: text('status').notNull().default('new'), notificationStatus: text('notification_status').notNull().default('pending'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const verifiedMembers = pgTable('verified_members', { id: text('id').primaryKey(), name: text('name').notNull(), occupation: text('occupation').notNull(), stateOfOrigin: text('state_of_origin').notNull(), currentState: text('current_state').notNull(), impact: text('impact').notNull(), contribution: text('contribution').notNull(), office: text('office').notNull(), imageUrl: text('image_url'), published: boolean('published').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const executives = pgTable('executives', { id: text('id').primaryKey(), name: text('name').notNull(), occupation: text('occupation').notNull(), stateOfOrigin: text('state_of_origin').notNull(), currentState: text('current_state').notNull(), impact: text('impact').notNull(), contribution: text('contribution').notNull(), office: text('office').notNull(), imageUrl: text('image_url'), published: boolean('published').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })

export const schema = { user, session, account, verification, siteSettings, homepageContent, programs, impactStories, posts, mediaAssets, donations, volunteers, verifiedMembers, executives }
