import Link from 'next/link'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import { auth } from '@/lib/auth'

export const dynamic = 'force-dynamic'

const managers = ['About us','Programs','Stories of impact','News & events','FAQs & settings','Donation options']
export default async function AdminPage() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) redirect('/admin/login'); return <main className="min-h-screen bg-[#f3f6f1] px-5 py-10 text-[#17332d] lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#c56b4b]">Admin dashboard</p><h1 className="mt-2 text-4xl font-semibold">Good morning, {session.user.name.split(' ')[0]}.</h1><p className="mt-2 text-sm text-[#64776e]">{session.user.email}</p></div><Link href="/" className="rounded-full border border-[#b9c9bd] px-4 py-2 text-sm font-bold">View site</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['₦1.24m','Total donations'],['28','Volunteer submissions'],['7','Active programs'],['12','Stories published']].map(([v,l])=><div key={l} className="rounded-2xl bg-white p-6"><p className="text-3xl font-semibold text-[#c56b4b]">{v}</p><p className="mt-2 text-sm text-[#64776e]">{l}</p></div>)}</div><section className="mt-8 rounded-3xl bg-white p-7"><h2 className="text-xl font-semibold">Content managers</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{managers.map(item=>{const href=item==='Programs'?'/admin/programs':'#'; return <Link href={href} key={item} className="rounded-2xl border border-[#d9e1d8] p-5 text-left font-semibold transition-colors hover:border-[#c56b4b]">{item}<span className="mt-2 block text-sm font-normal text-[#64776e]">Manage content →</span></Link>})}</div></section><section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl bg-[#17332d] p-7 text-[#f7f4eb]"><h2 className="text-xl font-semibold">Needs your review</h2><div className="mt-6 space-y-5">{[['8','Donation confirmations'],['6','Volunteer applications'],['3','Story submissions']].map(([n,l])=><div key={l} className="flex items-center justify-between border-b border-[#36564b] pb-4"><span className="text-[#b9c9bd]">{l}</span><strong className="text-2xl text-[#e5b65c]">{n}</strong></div>)}</div></div><div className="rounded-3xl border border-[#d9e1d8] p-7"><h2 className="text-xl font-semibold">Quick actions</h2><div className="mt-5 flex flex-wrap gap-3"><Link href="/programs" className="rounded-full bg-[#e5b65c] px-4 py-3 text-sm font-bold">Preview programs</Link><Link href="/stories" className="rounded-full border border-[#b9c9bd] px-4 py-3 text-sm font-bold">Preview stories</Link></div></div></section></div></main> }
