'use client'

import { useState } from 'react'
import { Save } from 'lucide-react'
import { saveHomepageContent } from '@/app/actions/homepage'

type Content = { heroEyebrow:string; heroTitle:string; heroDescription:string; promiseLabel:string; promiseText:string; peopleReached:string; peopleReachedLabel:string; metric1Value:string; metric1Label:string; metric2Value:string; metric2Label:string; metric3Value:string; metric3Label:string; metric4Value:string; metric4Label:string; directProgrammes:number; fundraising:number; administration:number }
const textFields: [keyof Content,string][] = [['heroEyebrow','Hero eyebrow'],['heroTitle','Hero title'],['heroDescription','Hero description'],['promiseLabel','Promise label'],['promiseText','Promise text'],['peopleReached','People reached number'],['peopleReachedLabel','People reached label'],['metric1Value','Metric 1 number'],['metric1Label','Metric 1 label'],['metric2Value','Metric 2 number'],['metric2Label','Metric 2 label'],['metric3Value','Metric 3 number'],['metric3Label','Metric 3 label'],['metric4Value','Metric 4 number'],['metric4Label','Metric 4 label']]
const numberFields: [keyof Content,string][] = [['directProgrammes','Direct programmes %'],['fundraising','Fundraising %'],['administration','Administration %']]
export function AdminHomepageEditor({ initial }: { initial: Content }) {
  const [form,setForm]=useState<Content>(initial); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
  const update=(key:keyof Content,value:string)=>setForm((current)=>({...current,[key]:value}))
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');try{await saveHomepageContent(form);setMessage('Homepage updated successfully.')}catch(error){setMessage(error instanceof Error?error.message:'Unable to save homepage')}finally{setBusy(false)}}
  return <form onSubmit={submit} className="space-y-8">{message&&<p role="status" className="rounded-xl bg-[#eaf0e7] px-4 py-3 text-sm font-semibold text-[#315d4d]">{message}</p>}<section className="rounded-[2rem] bg-white p-6 shadow-sm"><h2 className="text-2xl font-semibold">Homepage copy</h2><p className="mt-2 text-sm text-[#64776e]">Edit the words visitors see on the hero and promise sections.</p><div className="mt-6 grid gap-5">{textFields.slice(0,5).map(([key,label])=><label key={key} className="grid gap-2 text-sm font-semibold">{label}{key==='heroDescription'?<textarea rows={4} value={String(form[key])} onChange={(e)=>update(key,e.target.value)} className="rounded-xl border border-[#cbd8cc] px-4 py-3 font-normal"/>:<input value={String(form[key])} onChange={(e)=>update(key,e.target.value)} className="rounded-xl border border-[#cbd8cc] px-4 py-3 font-normal"/>}</label>)}</div></section><section className="rounded-[2rem] bg-white p-6 shadow-sm"><h2 className="text-2xl font-semibold">Impact numbers</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">{textFields.slice(5).map(([key,label])=><label key={key} className="grid gap-2 text-sm font-semibold">{label}<input value={String(form[key])} onChange={(e)=>update(key,e.target.value)} className="rounded-xl border border-[#cbd8cc] px-4 py-3 font-normal"/></label>)}</div></section><section className="rounded-[2rem] bg-white p-6 shadow-sm"><h2 className="text-2xl font-semibold">Where the money goes</h2><p className="mt-2 text-sm text-[#64776e]">These percentages must add up to 100.</p><div className="mt-6 grid gap-5 sm:grid-cols-3">{numberFields.map(([key,label])=><label key={key} className="grid gap-2 text-sm font-semibold">{label}<input type="number" min="0" max="100" value={Number(form[key])} onChange={(e)=>setForm({...form,[key]:Number(e.target.value)})} className="rounded-xl border border-[#cbd8cc] px-4 py-3 font-normal"/></label>)}</div></section><button disabled={busy} className="inline-flex items-center gap-2 rounded-full bg-[#c56b4b] px-6 py-4 font-bold text-white disabled:opacity-60"><Save size={17}/>{busy?'Saving…':'Save homepage changes'}</button></form>
}
