import { getPublishedMembers } from '@/app/actions/members'
import { PageIntro, SiteShell } from '@/components/site-shell'

export const dynamic = 'force-dynamic'

export default async function VerifiedMembersPage() {
  const members = await getPublishedMembers()
  return <SiteShell><main><PageIntro eyebrow="Verified members" title="The people who make this work possible." text="Meet the dedicated members of Bonded Friends Outreach Initiative and learn how they serve their communities."/><section className="mx-auto grid max-w-7xl gap-6 px-5 pb-24 sm:grid-cols-2 lg:grid-cols-3 lg:px-8">{members.length ? members.map((member) => <article key={member.id} className="overflow-hidden rounded-[2rem] border border-[#d9e1d8] bg-white"><div className="aspect-[4/3] bg-[#e5b65c]">{member.imageUrl ? <img src={member.imageUrl} alt={member.name} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-7xl font-semibold text-[#17332d]">{member.name.slice(0, 1)}</div>}</div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#c56b4b]">{member.office}</p><h2 className="mt-3 text-2xl font-semibold">{member.name}</h2><p className="mt-2 font-medium text-[#64776e]">{member.occupation}</p><dl className="mt-5 grid gap-3 text-sm leading-6"><div><dt className="font-bold text-[#17332d]">Origin</dt><dd className="text-[#64776e]">{member.stateOfOrigin}</dd></div><div><dt className="font-bold text-[#17332d]">Based in</dt><dd className="text-[#64776e]">{member.currentState}</dd></div><div><dt className="font-bold text-[#17332d]">Impact</dt><dd className="text-[#64776e]">{member.impact}</dd></div><div><dt className="font-bold text-[#17332d]">Contribution</dt><dd className="text-[#64776e]">{member.contribution}</dd></div></dl></div></article>) : <p className="rounded-3xl border border-dashed border-[#cbd8cc] p-8 text-[#64776e]">Verified member profiles will appear here soon.</p>}</section></main></SiteShell>
}
